services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: paint-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  pdf-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: paint-pdf-service
    ports:
      - "7690:7690"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
    restart: unless-stopped
